/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample2;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Song song1 = new Song("WAP", 1);
        Song song2 = new Song("Casey Jones", 2);
        Song song3 = new Song("Happy Birthday", 3);
        Song song4 = new Song("Party in the USA", 4);

        Album album = new Album("The light side of the sun");

        album.addSong(song1);
        album.addSong(song2);
        album.addSong(song3);
        album.addSong(song4);

        Artist artist = new Artist("Spice Gurls");

        artist.addAlbum(album);


        //populate a map by csv not using connected lists in classess
        Map<Artist, Map<Album, List<Song>>> database = new HashMap<>();


        //populate a map with lists in classes
        Map<Artist, Album> database2 = new HashMap<>();

    }
}
